spring.application.name=transaction-service

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.cache.type=redis
spring.cache.redis.time-to-live=5m

spring.data.redis.connect-timeout=1s
spring.data.redis.timeout=1s

management.health.redis.enabled=false