server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://transaction-service:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/transfers/**