spring.application.name=api-gateway

server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/transfers/**

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/finflow
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/finflow/protocol/openid-connect/certs