spring.datasource.url=jdbc:postgresql://127.0.0.1:55433/finflow
spring.datasource.username=${DB_USERNAME:finflow}
spring.datasource.password=${DB_PASSWORD:finflow}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

