spring.application.name=transaction-service
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:postgresql://127.0.0.1:55433/finflow
spring.datasource.username=finflow
spring.datasource.password=finflow

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/finflow
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/finflow/protocol/openid-connect/certs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2.server.resource=TRACE
