spring.datasource.url=jdbc:postgresql://127.0.0.1:55433/finflow
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/finflow
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/finflow/protocol/openid-connect/certs